Repository swap-it-all/swap-it-be, pull requests merged in 2025-04, with the labels that each got.

#130 [fix] 물건 상세 조회에서 연결된 swap이 rejected 되지 않은 것만 조회 하는 것으로 변경
  src/main/java/com/example/swapit/repository/trade/TradesRepository.java
Labels: 🔧 fix

#131 [fix] 물건 목록 조회에 goodsTradeStatus 필드 추가
  src/main/java/com/example/swapit/common/exception/ErrorCode.java
  src/main/java/com/example/swapit/domain/dto/good/GoodsDto.java
  src/test/java/com/example/swapit/controller/GoodsControllerTest.java
  src/test/java/com/example/swapit/docs/GoodsControllerDocsTest.java
Labels: 🔧 fix, 🎈 refactor

#134 [fix] 스왑 목록 수정
  src/main/java/com/example/swapit/domain/ChatRooms.java
  src/main/java/com/example/swapit/domain/dto/trade/BaseTradeGoodsDto.java
  src/main/java/com/example/swapit/domain/dto/trade/MyGoodsDto.java
  src/main/java/com/example/swapit/domain/dto/trade/MyRequestDto.java
  src/main/java/com/example/swapit/domain/dto/trade/ReceivedRequestDto.java
  src/main/java/com/example/swapit/domain/dto/trade/TradeCountProjection.java
  src/main/java/com/example/swapit/repository/trade/TradesRepository.java
  src/main/java/com/example/swapit/service/TradesServiceImpl.java
  src/test/java/com/example/swapit/controller/TradesControllerTest.java
  src/test/java/com/example/swapit/docs/TradesControllerDocsTest.java
  src/test/java/com/example/swapit/service/TradesServiceTest.java
Labels: 🔧 fix, 🕹️ test

#135 [feat] 알림 수신 설정 변경 기능 추가
  src/main/java/com/example/swapit/controller/NotificationController.java
  src/main/java/com/example/swapit/domain/Users.java
  src/main/java/com/example/swapit/service/notification/NotificationService.java
  src/main/java/com/example/swapit/service/notification/NotificationServiceImpl.java
Labels: ✨ feature, 🔧 fix

#137 [fix] 알림 수신 잘못 되는 문제 해결
  src/main/java/com/example/swapit/common/exception/ErrorCode.java
  src/main/java/com/example/swapit/domain/ChatRooms.java
  src/main/java/com/example/swapit/domain/Trades.java
  src/main/java/com/example/swapit/service/ChatServiceImpl.java
  src/main/java/com/example/swapit/service/TradesServiceImpl.java
  src/test/java/com/example/swapit/service/ChatServiceTest.java
Labels: 🔧 fix, 🛠️ hotfix

#138 [fix] 거래 완료 시 채팅 전송
  src/main/java/com/example/swapit/domain/dto/chat/ChatStompResponseDto.java
  src/main/java/com/example/swapit/service/ChatServiceImpl.java
  src/main/java/com/example/swapit/service/TradesServiceImpl.java
Labels: 🔧 fix

#140 [fix] 구독 확인 후, 메세지 전송 수락 처리
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
Labels: ✨ feature, 🔧 fix

#141 [fix] 구독 확인 후, 메세지 전송 처리 로직 수정
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
Labels: 🔧 fix

#142 [hotfix] /app -> /topic으로 변환해서 차단하는 로직으로 변경
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
Labels: 🛠️ hotfix

#143 [hotfix] heartbeat 끊기
  src/main/java/com/example/swapit/config/websocket/WebSocketConfig.java
Labels: 🛠️ hotfix

#146 [feat] 웹소켓 구독 검증 로직 추가
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
  src/main/java/com/example/swapit/domain/dto/NotificationDto.java
  src/main/java/com/example/swapit/service/notification/NotificationEventListener.java
Labels: 🔧 fix, 🎈 refactor

#147 [fix] 웹소켓 핸드셰이크에서 principal 설정하도록 로직 추가
  src/main/java/com/example/swapit/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/swapit/config/websocket/JwtHandshakeHandler.java
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
  src/main/java/com/example/swapit/config/websocket/WebSocketConfig.java
  src/main/java/com/example/swapit/service/notification/NotificationEventListener.java
  src/test/java/com/example/swapit/service/notification/NotificationEventListenerTest.java
Labels: 🔧 fix

#151 test : 채팅에서 메세지 보낼 때 로그 조금 더 자세히 구성
  src/main/java/com/example/swapit/service/ChatServiceImpl.java
Labels: 🛠️ hotfix, 🕹️ test

#156 [chore] 토큰 검증 추가
  src/main/java/com/example/swapit/common/exception/ErrorCode.java
  src/main/java/com/example/swapit/service/AuthServiceImpl.java
  src/main/java/com/example/swapit/service/notification/NotificationEventListener.java
  src/main/resources/application-prd.yaml
Labels: 🔧 fix, 🎈 refactor

#157 [fix] 토큰 재발급 로직에 동기화처리 + 에러 검증 추가
  src/main/java/com/example/swapit/service/AuthServiceImpl.java
Labels: 🔧 fix

#165 [fix] 채팅 알림 전송 시, 해당 채팅방에 구독 중이라면 알림 보내지 않도록 수정
  src/main/java/com/example/swapit/config/websocket/WebsocketDestination.java
  src/main/java/com/example/swapit/service/notification/NotificationEventListener.java
Labels: 🔧 fix, 🎈 refactor

#163 [refactor] jwt token claim 이메일을 userId로 변경
  src/main/java/com/example/swapit/config/security/CustomUserDetails.java
  src/main/java/com/example/swapit/config/security/CustomUserDetailsService.java
  src/main/java/com/example/swapit/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/swapit/config/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/example/swapit/config/security/jwt/JwtProvider.java
  src/main/java/com/example/swapit/config/security/jwt/JwtService.java
  src/main/java/com/example/swapit/config/websocket/JwtHandshakeHandler.java
  src/main/java/com/example/swapit/config/websocket/StompHandler.java
  src/main/java/com/example/swapit/repository/TokensRepository.java
  src/main/java/com/example/swapit/service/AuthServiceImpl.java
  src/main/java/com/example/swapit/service/ChatServiceImpl.java
  src/main/java/com/example/swapit/service/CurrentUserServiceImpl.java
  src/test/java/com/example/swapit/service/AuthServiceTest.java
Labels: 🔧 fix, 🎈 refactor, 🕹️ test

#167 [docs] 아동 안전 표준 정책 페이지 추가
  src/main/java/com/example/swapit/controller/DocsController.java
  src/main/resources/templates/docs/policy/kids-policy.html
Labels: 📜 docs
